### PR TITLE
Replaced sync methods with corresponding async versions

### PR DESCRIPTION
**Pull request by semihokur**
I am Semih Okur, a PhD student in the CS department at the University of Illinois. I'm currently doing research on asynchronous programming in phone applications. I found many misuses of async/await keywords in Windows Phone applications. One typical misuse is that developers use synchronous method calls in async methods. However, these synchronous method calls have corresponding asynchronous versions in .NET API.

I found some opportunities in your application and created a pull request for the patch

### CODE REVIEW

**Comment by dotMorten** [comment]
Thank you for taking your time to review this. However I would have to disagree with you. By adding an await in that loop, you are introducing a context switch an enormous amount of times. This would be highly undesirable. If anything the very first call in the method (await ReadAsStreamAsync) could use a .ConfigureAwait(false), which would remaining part of the method will continue to run off-thread with no more context switches (but if you dig higher up in the call stack you would know we are already on a background thread). Switching threads is VERY expensive and shouldn't be taken lightly. For this particular code, we are dealing with writing a byte array to an already in-memory byte stream, where the overhead of adding this await wouldn't buy us anything. In fact the compiler would add a significantly amount of code (roughly about 100 statements ) to perform this, which is totally overkill.
It's completely wrong when you think that adding async methods all over the place makes your code better. I don't hope you are submitting these types of pull requests all over github just to prove an (invalid) point.

**Comment by semihokur** [comment]
The transformation is done automatically by the tool. I agree that this transformation is not good case for async because of the loop. The tool already checks these kind of cases which don't fit for async/await; but there should be some bug about it. 

For sure, the tool does not transform all potential calls with async. I don't think that adding async methods make the code better. You cannot put ConfigureAwait(false) automatically unless you decide which data structures are created by UI thread.

**Comment by dotMorten** [comment]
I'm not clear why you would want to do this automatically.

**Comment by semihokur** [comment]
Can you send me an email (semih.okur@gmail.com)? I guess you don't use email address I got from your commits.

**Comment by dotMorten** [comment]
Please don't submit pull requests that are just generated by a tool and hasn't been reviewed and performance tested. You are confusing a lot of people on github who doesn't know any better and making their code worse.

**Comment by dotMorten** [comment]
Just to go back to your original statement "One typical misuse is that developers use synchronous method calls in async methods". This is such a wrong blanket statement and shows you completely lack the understanding of how multi threading and the TPL works. That's kinda worrying for someone who claims to have a phd.

**Comment by semihokur** [comment]
It's an advanced tool which allows refactoring from APM/EAP to async/await and detects misuses of async/await collaborated with Microsoft Research and funded by Microsoft SEIF 2013 award. For sure, it will miss some cases in the beginning. 

For my statement, I try to be as simple as in the explanation of misuse. I don't want to complicate the minds of developers who even do not know how async/await works under the hood. When they request clarification, I explain in more detail. 

If you want to know more about parallel programming in .NET, please look at my top-tier publication: http://www.learnparallelism.net/

You cannot talk with me in such way, especially as a comment to pull request. If you want to talk with me more, please send me an email. I would be very happy to talk about my project and discuss about it with you. 

Take care!

**Comment by dotMorten** [comment]
My problem with this is that you admit that this is still a tool in development still has flaws, yet you have submitted several pull requests on GitHub with it. It doesn't really matter how many awards you have or who you collaborate with. People's hard work shouldn't be your guinea pigs without up-front approval. Your pull request is not clear that this is changes made by a tool and could very well be wrong. That's what I'm calling you out on. I'm sorry if you feel I'm rough on you, but I call a spade a spade when I see it. And I prefer doing this out in the open because I stand by what I say.

**Pull request closed without merging**
